name: release build

on:
  - push

jobs:
  test:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Cache rust build artifacts
        uses: Swatinem/rust-cache@v2

      - name: Build release target
        run: cargo build --release
